version: '3.8'

services:
  web:
    build: .
    container_name: flask_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/company_search
      - SECRET_KEY=your_secret_key_here
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - JWT_ACCESS_TOKEN_EXPIRES=1209600  # 14天，與前端cookie設置一致
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - app-network
    command: gunicorn --bind 0.0.0.0:5000 "app:app"  # 修改這裡

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"  # 使用5433端口避免衝突
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=company_search
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: